### ISSUE TITLE
Find bus route data

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#1]

**Comment by mem48** [comment]
Bus lanes in OSM data so closing

**Comment by mvl22** [comment]
Can you clarify (perhaps by changing the title) what this was aimed at?

Bus lanes are (spottily) in OSM

If trying to get actual routes, Relations exist, together with bus stop locations, as shown by this rendering:
https://www.openstreetmap.org/#map=16/52.2017/0.1279&layers=T
https://www.openstreetmap.org/#map=18/51.49522/-0.10041&layers=T
