### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#14]

**Comment by Robinlovelace** [comment]
Here are some ideas: 
![image](https://cloud.githubusercontent.com/assets/1825120/24213848/be6c438c-0f2b-11e7-9069-6cbda18646cf.png)

**Comment by Robinlovelace** [comment]
So far the head-on cycle wheel/bridge is the favourite.

**Comment by mvl22** [comment]
Portrait-orientation logos are always a complete pain whenever you try to use them for anything practical.

**Comment by Robinlovelace** [comment]
Fair point. How about the top left one? @johnparkin28 your input welcome. 

What about the bottom left one? Or the Portrait one with a big CyIPT lettering to the left?

**Comment by johnparkin28** [comment]
Entirely take the point about portrait. How above a side on of he bridge that looks like a bicycle wheel? They always tell me that a logo that has a general upward movement to the right is a logo that is positive and wins hearts and minds. Does this imply that the route over the bridge should lift off to the right hand side? I have just emailed a suggestion to Robin (I am not clever enough to get it on github, sorry).

**Comment by Robinlovelace** [comment]
Here's my masterpiece: 

![image](https://cloud.githubusercontent.com/assets/1825120/24255952/d1fb0e34-0fde-11e7-967e-79f7f1b128aa.png)

Thinking about it I think there may be merit to completely separating the text from the logo's shape.

**Comment by Robinlovelace** [comment]
Prefering [this](https://www.flickr.com/photos/97888609@N02/33566912706/in/dateposted-public/) now.

![image](https://cloud.githubusercontent.com/assets/1825120/24256998/8a67e030-0fe1-11e7-82a6-09539a20233c.png)

Portraity enough for you Martin? @mvl22

**Comment by johnparkin28** [comment]
Yep, like that.

Regards
John Parkin CEng FICE FCIHT FCILT, Professor of Transport Engineering
University of the West of England, Centre for Transport and Society
Frenchay Campus, Coldharbour Lane Bristol, BS16 1QY, UK
t: +44 (0)117 32 86367 m: +44 (0)7848 029 902 Skype: john.parkin9, Twitter: @JohnParkin28 https://uk.linkedin.com/pub/john-parkin/6/840/89b
Publications: http://eprints.uwe.ac.uk/view/author/Parkin=3AJohn=3A=3A.html
http://www1.uwe.ac.uk/et/research/cts and https://www.facebook.com/ctsuwe

**Comment by mem48** [comment]
![logoidea](https://cloud.githubusercontent.com/assets/15819577/25090019/fac68462-2378-11e7-9f24-a51094b34192.png)

**Comment by mem48** [comment]
![logoidea2](https://cloud.githubusercontent.com/assets/15819577/25090405/e2b951fe-237a-11e7-8ec9-e71a9b68397d.png)

**Comment by MaiaKelly** [comment]
Hello - Here are three drafts - let me know what you think/ which you prefer! 
![idea5](https://cloud.githubusercontent.com/assets/27705164/25104475/634af466-23b8-11e7-9cb4-bb29dd4209be.png)
![robins idea](https://cloud.githubusercontent.com/assets/27705164/25104492/723231b0-23b8-11e7-9646-18b4d842b69b.png)
![iscoteur](https://cloud.githubusercontent.com/assets/27705164/25104527/9af339b4-23b8-11e7-8ac4-6807946ce0bd.png)

**Comment by MaiaKelly** [comment]
Here is what the logo might look like on letter heads. Question - should we keep the corner things? It was inspired by Architectural Blue prints.

![image](https://cloud.githubusercontent.com/assets/27705164/25104658/18ca606a-23b9-11e7-84ac-7f34473edac4.png)
![image](https://cloud.githubusercontent.com/assets/27705164/25104703/4024eee6-23b9-11e7-91d7-7ac1a5d91e88.png)
![image](https://cloud.githubusercontent.com/assets/27705164/25104739/6a3be734-23b9-11e7-80b9-3c566d10615f.png)

**Comment by Robinlovelace** [comment]
Great work!

**Comment by mvl22** [comment]
I don't have strong views about the logo, and happy to go ahead with any of those three, but I do just want to remind people that the concept of this project is about identifying missing infrastructure. While I like visually the design that's just been produced, and it's quite clever in merging the concept of a bike and a bridge, I'm not sure that it quite tells that story yet. That said, logos don't always have to be quite so literal, but just a point to bear in mind.

**Comment by Robinlovelace** [comment]
My preference: the second one with the bike on the one side and the bridge cables on the other. Thought: the end of the bridge could be made dotted to show that it's in the process of filling in missing infrastructure. Doable @MaiaKelly? 

What do you think @johnparkin28 and @mem48?

**Comment by mvl22** [comment]
I'd suggest reversing the bike order so that it is heading inwards, rather than away.

**Comment by Robinlovelace** [comment]
Good plan Martin. So it would be a little like [this](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=logo.xml#Uhttps%3A%2F%2Fraw.githubusercontent.com%2FgeocomPP%2Fsdv%2Fmaster%2Flogo.xml). 

![image](https://cloud.githubusercontent.com/assets/1825120/25136722/acb552e6-244d-11e7-9d37-e5b88fd93892.png)

**Comment by Robinlovelace** [comment]
Or this, with the dotted line representing infrastructure to be filled-in:

![image](https://cloud.githubusercontent.com/assets/1825120/25136864/0e55b630-244e-11e7-94d6-8e62c2fe7338.png)

**Comment by Robinlovelace** [comment]
Hi @MaiaKelly we've just discussed this and have come up with a consensus on a solution I think: your second option but simply with the bike turned the other way and 'holes' (e.g. dashes in the line) to be filled in. I think having the letters on the right hand side, as you did originally, is better. 
@mvl22 sound right, anything to add?

Then we're good to go! Let's catch up later in the week on it.

**Comment by MaiaKelly** [comment]
![newlogo](https://cloud.githubusercontent.com/assets/27705164/26583054/82a1afcc-453b-11e7-9e2a-001f44efe6cd.jpg)
![newlogo2](https://cloud.githubusercontent.com/assets/27705164/26583055/82ab4424-453b-11e7-87af-8261d2a86df3.jpg)

**Comment by MaiaKelly** [comment]
Hi team. Sorry for the slow reply I've been on annual leave. I've done a fade rather than dotted lines for the bridge - as I thought it looked a bit slicker.. but I'm happy to change it to dotted lines if you prefer. I also had a play around with some other concepts in my spare time (attached below). I think the simpler the logo the better (for using on small letter heads etc if needed). Let me know if you need any changes, apologies for not being able to offer anything more professional. 
![test](https://cloud.githubusercontent.com/assets/27705164/26583332/b3c5e59a-453c-11e7-9b86-5520cb91ff30.jpg)
![test2](https://cloud.githubusercontent.com/assets/27705164/26583335/b3ce85ce-453c-11e7-85ec-37e237af203e.jpg)
![test3](https://cloud.githubusercontent.com/assets/27705164/26583333/b3cbe95e-453c-11e7-8f57-874b903b7f32.jpg)
![test5](https://cloud.githubusercontent.com/assets/27705164/26583334/b3ccd65c-453c-11e7-97ee-a8a55a602249.jpg)

**Comment by Robinlovelace** [comment]
Hey @MaiaKelly these are all awsome, thanks loads.

I think the fade out works really well, great idea. I agree re. simplicity so my favourite is this one:

![](https://cloud.githubusercontent.com/assets/27705164/26583055/82ab4424-453b-11e7-87af-8261d2a86df3.jpg)

**Comment by Robinlovelace** [comment]
@mvl22 @mem48 @johnparkin28 you happy to go with this?

**Comment by johnparkin28** [comment]
Yep, happy.

Regards
John Parkin CEng FICE FCIHT FCILT, Professor of Transport Engineering
University of the West of England, Centre for Transport and Society
Frenchay Campus, Coldharbour Lane Bristol, BS16 1QY, UK
t: +44 (0)117 32 86367 m: +44 (0)7848 029 902 Skype: john.parkin9, Twitter: @JohnParkin28 https://uk.linkedin.com/pub/john-parkin/6/840/89b
Publications: http://eprints.uwe.ac.uk/view/author/Parkin=3AJohn=3A=3A.html
http://www1.uwe.ac.uk/et/research/cts and https://www.facebook.com/ctsuwe

**Comment by Robinlovelace** [comment]
Job done. Thanks loads @MaiaKelly this is awesome work and will help give the project a visual identity.

**Comment by MaiaKelly** [comment]
![new 3 copy](https://cloud.githubusercontent.com/assets/27705164/26628386/ccc177e4-45f5-11e7-9f6c-27f4cf1b5d7d.jpg)

I also made this one on the train just now, I had no wifi so didn't see you're last messages. I'll throw it on the table anyway so you have all the options. It was made with @mvl22 's comment in mind - that maybe the logo could do a bit more to tell a story about identifying missing infrastructure (which I agree with!). I think the bridge is a bit more obviously a bridge in this one. 

But otherwise ace, nice to have the job done. Hope the rest of the project goes well and glad to be able to support it.

**Comment by Robinlovelace** [comment]
That's cool - a nice idea 4sure but, unless there are any objections, I'd say we stick with the other one which has a real clean and easily recognisable shape. Thanks so much for this.

**Comment by Robinlovelace** [comment]
This is my second favourite btw so if there is a strong preference for this I'm very easily persuadable to change it:

![image](https://cloud.githubusercontent.com/assets/1825120/26629025/82277ac8-45f8-11e7-8a52-cf695e6d3668.png)
