### ISSUE TITLE
Develop typology of barrier types - roads

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#17]

**Comment by Robinlovelace** [comment]
Heads up @johnparkin28, your input welcome here.

**Comment by johnparkin28** [comment]
Yes, sure, I will do something on this.

**Comment by Robinlovelace** [comment]
![readme-unnamed-chunk-9-1](https://cloud.githubusercontent.com/assets/1825120/24654906/bb4c37ae-1933-11e7-8a36-68cd3d34baf9.png)

**Comment by Robinlovelace** [comment]
He's a representation of quietness of a subset of lines in Bristol: http://rpubs.com/RobinLovelace/265530

**Comment by Robinlovelace** [comment]
And another visualisation of that: http://rpubs.com/RobinLovelace/265544

**Comment by johnparkin28** [comment]
[Data to model route choice.docx](https://github.com/cyipt/cyipt/files/901948/Data.to.model.route.choice.docx)

I have also uploaded the accident analysis and prevention manuscript to the other location as per your other email.

I think it important that we try to describe beforehand what is proposed, I think this prevents problems downstream. Might Malcolm (not sure what symbol I put here to direct a message to Malcolm sorry (@malcolmmorgan ?)have a go at creating a methodology paper on this issue, based on the AAP paper, this attachment and also the other interesting list of infrastructure people have suggested?
https://github.com/mem48

**Comment by Robinlovelace** [comment]
Many thanks John. @mem48 I think @johnparkin28 was trying to tag you in that last line!

**Comment by Robinlovelace** [comment]
Sounds like we're almost there on this. Please link to the road types you've generated @mem48 and close if appropriate.
