### ISSUE TITLE
CycleStreets to add an API frontend to the batch routing system

### ISSUE THREAD

**Issue by mvl22** [cyipt/cyipt#19]
The current batch routing system is currently only GUI-based, though this is implemented as MVC.

So an API frontend just needed to be added as an alternative controller.

The job start mechanism would return a URL that the caller can poll for the result and then retrieve over HTTP(S).

**Comment by Robinlovelace** [comment]
How goes this one? Will be useful when running regession model on modified network.

**Comment by mvl22** [comment]
This is next on my list once the traffic counts stuff is polished off. Very keen to get on with this one.

**Comment by mvl22** [comment]
Merging this into #20.
