### ISSUE TITLE
Cycle lane widths

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#21]
Recommended from [Sustrans](http://www.sustrans.org.uk/sites/default/files/file_content_type/sustrans_handbook_for_cycle-friendly_design_11_04_14.pdf): 1 m for a cyclist, 2.5 for 2:

![image](https://cloud.githubusercontent.com/assets/1825120/24695609/58f030fa-19de-11e7-8833-76c00cc9a73e.png)

For @mem48 and @mvl22 and @johnparkin28 what's the threshold in cyclists per hour (CPU is it?) to justify 2 lane one-way cycle paths?

What's the equivalent for cars?

**Comment by mvl22** [comment]
> Recommended from Sustrans: 1 m for a cyclist, 2.5 for 2:

Be aware that the Sustrans "Handbook for cycle-friendly design" has been very heavily criticised by the cycle campaigning community. It was published on the same day as Making Space for Cycling, and received condemnation ("got a bit of a kicking from many people" [1]; "sadly is not nearly the document that it should be" [2]) for setting such low standards.

Sustrans fairly quickly said that they planned to revise it:
http://www.sustrans.org.uk/blog/principles-and-processes-cycle-friendly-design

I would therefore want to see any such figures above subject to review. I'm not saying they are necessarily wrong but at this stage I would not assume they are agreed in general.

Also, I think the diagrams you're showing are purely about physics and not an actual recommendation for infrastructure width. No serious campaigner would work on the basis of infrastructure that is 1m wide.

2m is the recommended figure in many pieces of guidance:
https://www.camcycle.org.uk/resources/cyclelanewidths/

and in Cambridge we work on a 2.1m minimum recommendation when judging infrastructure proposals. So far, only three schemes in Cambridge have met that threshold.

Our academic contacts should be able to get some better references.

[1] https://aseasyasridingabike.wordpress.com/2015/06/05/sustrans-cycle-friendly-design-manual-part-1/

[2] http://www.aviewfromthecyclepath.com/2014/05/sustrans-handbook-for-cycle-friendly.html

**Comment by mvl22** [comment]
Some opinions from Camcycle:

https://www.camcycle.org.uk/newsletters/127/article4.html

**Comment by mvl22** [comment]
Here's the article I was looking for earlier, dealing with the trade-offs involved in one-way vs. two-way tracks:

https://www.camcycle.org.uk/newsletters/123/article9.html

ref @mem48

**Comment by mvl22** [comment]
The video in this article is an excellent example of why narrow cycle lanes can cause more harm than good.

http://road.cc/content/news/220506

@mem48

**Comment by mem48** [comment]
Closing as discussion over will feed into later discussions as needed
