### ISSUE TITLE
Access Cyclescape data

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#23]
Preferably as geojson in the example-data repo and pls post code that did it here.

**Comment by mvl22** [comment]
API at:
http://petstore.swagger.io/?url=http://www.cyclescape.org/api/swagger_doc

I will probably ask Nikolai to make a CSV output option.

**Comment by mem48** [comment]
At the request of @mvl22 the variables that the PCT used from the Cyclestreets:

length, time, waypoint, cum_hill, change_elev, dif_max_min, up_tot, down_tot,  av_incline, co2_saving, calories, busyness,

**Comment by mvl22** [comment]
Malcolm you've posted that to the wrong issue in wrong repo...

**Comment by Robinlovelace** [comment]
@mvl22 could you provide an example request that downloads cyclescape data for Bristol. Then we can close this I think.

**Comment by mvl22** [comment]
https://www.cyclescape.org/api/issues.json?page=1&per_page=100&bbox=-2.770958%2C51.399420%2C-2.280350%2C51.499126

For future reference: I did this by going to the Bikedata site, switching on Issues, navigating to Bristol, and seeing the request in the Network requests part of the console.

It can also be determined by using the API documentation available at:
https://www.cyclescape.org/api/
but the Bikedata example is a working implementation so quick to grab an example without having to work out the Bbox.

**Comment by Robinlovelace** [comment]
Great stuff, thanks for the demo.
