### ISSUE TITLE
Split OSM lines at junctions

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#26]
Cycling potential and thus appropriate infrastructure can change at every junction, as the number of cyclists can increase and decrease. However, OSM data often represents a road as a long continuous line crossing many junctions. 

So we need a way to break lines at every junction.

The first attempt used ArcGIS Feature to Line http://pro.arcgis.com/en/pro-app/tool-reference/data-management/feature-to-line.htm which works but is not a long-term solution. Need an R version of this function.

**Comment by mem48** [comment]
Related to Issue #12

**Comment by mvl22** [comment]
> So we need a way to break lines at every junction.

I saw #24 where this was first raised.

This step can obviously either be done at the routing engine output level, or at the post-processing GIS/R stage. The question is thus which is preferable, architecturally.

As you imply, this seems best done at the GIS/R level. CycleStreets aims to maintain the purity of the OSM data, and if a non-CycleStreets upstream data source was used, it is likely that the same issue would then arise, as breaking Ways is a domain-specific task, so it would accordingly probably be best done at the GIS/R level.

**Comment by mem48** [comment]
I agree, however it is not an easy GIS problem. Is there a way to get the junction locations out of OSM as points? #27

**Comment by mvl22** [comment]
Yes, looks like we have those, so will work on getting those out too.

**Comment by mvl22** [comment]
I've added the 'joints' as we call them - nodes that are actually junction points rather than just nodes within a Way.

This dataset is merely the locations, and does not include scorings (e.g. the set of penalties applied to each turn combination). I can get those out but it will be a more complex query and is probably more than we need at this stage.

**Comment by Robinlovelace** [comment]
Please add code as per #30 - then we should have a function in R to do that.

**Comment by Robinlovelace** [comment]
@mvl22 just to clarify - splitting the lines at the junctions is different from tagging the junctions - hence 2 issues.

**Comment by mvl22** [comment]
```
SELECT
	mp.nodeId,
	IFNULL(mj.degree, 0) AS joinsLegs,
	mn.longitude,
	mn.latitude
FROM map_point mp
LEFT JOIN map_joint mj ON mj.id = mp.jointId
JOIN map_noodle mn ON mp.nodeId = mn.nodeId
JOIN map_way AS mw ON mp.wayId = mw.id
WHERE
	    ST_INTERSECTS( ST_ENVELOPE (ST_LINESTRINGFROMTEXT('LINESTRING(0.02369 52.12316, 0.25509 52.24945)')) , mw.points)
	AND mp.jointId > 0
GROUP BY mp.jointId
ORDER BY nodeId
``` 

As I say, this will in practice be fairly useless if you're using R's osmdata or OSM XML directly.

**Comment by Robinlovelace** [comment]
Nice - thanks for sharing @mvl22
