### ISSUE TITLE
Download Junction Locations as Point from OSM

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#27]
We need point location data for every junction, so a bunch of GIS reasons.
We need to figure out how to get that out of OSM

**Comment by Robinlovelace** [comment]
Re-opening as I'd like to demonstrate an R solution and see the sql code pls @mvl22

**Comment by Robinlovelace** [comment]
Well I can get all the roundabouts no problem: http://rpubs.com/RobinLovelace/293008

Code: see commit below.

**Comment by Robinlovelace** [comment]
Based on this: http://wiki.openstreetmap.org/wiki/Key:junction

**Comment by Robinlovelace** [comment]
But struggling to find out how to get points representing all road intersections including cross roads and T junctions...

**Comment by Robinlovelace** [comment]
Some roundabouts in any case http://rpubs.com/RobinLovelace/293008 : 

![image](https://user-images.githubusercontent.com/1825120/28467901-48079144-6e29-11e7-9406-140c8d1cb6e6.png)
