### ISSUE TITLE
Generate traffic count estimates from DfT's open Traffic Count data

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#31]

**Comment by mvl22** [comment]
I think I now understand the data format, and have worked out which of the several downloads to use, so am working on an SQL script to process these, which naturally I'll put in the repo.

**Comment by Robinlovelace** [comment]
Fantastic. This will also make @jf1 happy.

**Comment by jf1** [comment]
I believe Alex Ingram @nuttyxander has already done quite a bit of work on this so perhaps worth contacting him first.

For reference, I'm less interested in the high-PCU counts from roads that the DfT regularly counts - I'm much more interested in modelling from dead-end roads to the points where estimated traffic levels will reach 500, 1000, etc PCUs, probably up to 3,000 but up to 5,000 might be useful if that's practical. I've discussed this in detail with @RachelAldred who's tested this principle on a single street using: number of households, car ownership rates and car usage rates.

To create a NationalPCU dataset that covers both busy and quiet roads I believe both approaches would be required.

**Comment by nuttyxander** [comment]
Yeah, I've got this data processed and lying around. Currently published on google fusion tables for:
AADF - https://fusiontables.google.com/DataSource?docid=1WBfLu0V0XYr7Flwq9dtPBSuFcsm02iwJFVPX6B-q#map:id=3
and Raw Hourly - https://fusiontables.google.com/DataSource?docid=10UULmRznAtzE6wiOuKRjYDiRd34MBpxEQ1Oq-mLJ#map:id=3

The data does have issues in it which I currently have a script to work around (all kinds of formatting and other screw-ups) and in addition DfT are remarkably quiet in explaining that though they quote an AADF for every count for every year they don't really do each one every year (and in fact the raw data lets you see just how long ago the last count was, unless IIRC it's a purely automatic counter converted in which case you never see even the raw count).

Data will refresh in around May/June to see what 2016 shows. Which will be interesting for e.g. the superhighways in London.

The modelling of PCU over the network is a much trickier job. The examples I've seen are interesting but I think could be improved with more attention paid to them and perhaps even a little more testing in the field. Alternately, perhaps TfL at least could be encouraged to share their own modelling a bit more widely.

**Comment by Robinlovelace** [comment]
Many thanks for your input Alex - really useful. Note: this isn't core to the CyIPT project but if we can integrate PCU estimates that could greatly help our work to prioritise infrastructure interventions.

**Comment by Robinlovelace** [comment]
Heads up @nuttyxander and others: this shows how R and PostGIS can be integrated - may be of use/interest in relation to this work: http://info.crunchydata.com/blog/r-analytic-functions-in-postgis

**Comment by Robinlovelace** [comment]
Proof of method (result of a 2 stage process involving R and SQL): http://rpubs.com/RobinLovelace/280638

Results (preliminary):

Note that this omits roads without names - will join them on next.

Reproducible code (R): https://github.com/cyipt/cyipt/blob/master/trafficcounts/test-traffic.R

Reproducible code by @mvl22 (PostgreSQL): https://github.com/cyipt/cyipt/blob/master/trafficcounts/trafficcounts.sql

Would like to convert the second one to a more concise and accessible (just as R is easier to install that an SQL db).

But not a priority. Priority is to use this in the regression model.

**Comment by mvl22** [comment]
> Reproducible code by @mvl22 (PostgreSQL):
> https://github.com/cyipt/cyipt/blob/master/trafficcounts/trafficcounts.sql

Actually you should really start from the .sh file in the [same folder](https://github.com/cyipt/cyipt/tree/master/trafficcounts) as that marshalls everything.

The code was adapted for MySQL, as that is what I had to hand, but the few places now where there is not portability have the Postgres code there also.

**Comment by mvl22** [comment]
The same data table is now wrapped in a simple GeoJSON API whose visualisation can be seen at:
http://bikedata.cyclestreets.net/trafficcounts/#14/52.2143/0.1336/mapnik

I'll add the documentation for the API to 
https://www.cyclestreets.net/api/v2/
once it's stable soon.
