### ISSUE TITLE
Progress report

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#32]

**Comment by Robinlovelace** [comment]
Deadline: 27th April

**Comment by mem48** [comment]
Done and sent

**Comment by Robinlovelace** [comment]
Suggest we send this Monday 5th.

**Comment by Robinlovelace** [comment]
Thanks for closing.

**Comment by Robinlovelace** [comment]
Sent for July - can re-open for August.

**Comment by Robinlovelace** [comment]
Last one was sent 1st Sept - this will be the 6th sent now.

Pls close when done @mem48

**Comment by mem48** [comment]
Report 6 has been sent to @Robinlovelace who is forwarding to DFT
