### ISSUE TITLE
Share how quietness algorithm works

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#35]
Agreement that greater internal scrutiny of the algorithm is needed before it can be used in CyIPT. The algorithm is not open source but Martin to investigate ways it can be shared internally.

**Comment by mvl22** [comment]
Action @si-the-pie - maybe send me a draft internally first so we can flesh out as much as possible and I can add any ideas in.

**Comment by Robinlovelace** [comment]
Update - modelling suggests this is really important. Just fitting against average 'quietness' we're getting R^2 of 0.89 but the model explains over 95% variability in cycling when we use the average 'busynance' that was pulled down from the pct routes with stplanr: https://github.com/cyipt/cyipt/blob/master/model-uptake.md

**Comment by Robinlovelace** [comment]
Nudge @mvl22 on this. Malcolm and I discussed this and would like to try to re-create this (or a similar score) locally. Could you share some pseudo-code that does this?

**Comment by Robinlovelace** [comment]
Action @mvl22 and @si-the-pie pls sit down and work through.

**Comment by mem48** [comment]
Just to reiterate there are 2 issues here:

1) Robin and I need to understand this a high level just so that we know it is producing meaningful results because there is a strong correlation between busyance score and the number of cyclists on a route.

2) When evaluating the benefits of a proposed scheme we want to be able to change the busyance of the route without needed to reroute through cyclestreets.net 

So we will have an algorithm which looks like:
n_cyclists <- f(n_commuters, distance, hilliness, busyance, etc)

We will propose building a cycle lane along part of the route and will need to compute a new busyance score for the route so we can calculate the new number of cyclists.

**Comment by si-the-pie** [comment]
I have started on this task. There are some existing notes, which though old are still correct at:
https://www.cyclestreets.net/journey/help/howitworks/#quietness

**Comment by Robinlovelace** [comment]
Great stuff - a more detailed note, preferably with some code showing the input variables, should be sufficient to represent interventions that increase quietness. Then I plan to build on this to estimate near-term uptake following specific interventions.

**Comment by mvl22** [comment]
Simon's written this - will meet with him shortly to go over it and add my input, and then post it here.

**Comment by Robinlovelace** [comment]
Great news.

**Comment by mvl22** [comment]
Now in busyness repo.
