### ISSUE TITLE
Get guidance from Dutch CROW Manual and other relevant tables from elsewhere

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#38]
Get English version for Dutch CROW manual or relevant tables

**Comment by mvl22** [comment]
Specifically, this is to get the provision chart which I believe is in there.

Other similar charts I will post below.

**Comment by mvl22** [comment]
![tumblr_inline_mu1cwzrmab1qfzwpk](https://cloud.githubusercontent.com/assets/361423/25199064/72fb502e-2541-11e7-82ed-c4763a5118ef.png)

http://pedestrianiselondon.tumblr.com/post/20170547370/cycleway-provision-from-the-experts

Not clear exactly what the original source of this was. Page implies this is derived from CROW.

**Comment by mvl22** [comment]
![tumblr_inline_mu1cssr1ih1qfzwpk](https://cloud.githubusercontent.com/assets/361423/25199123/a04efe86-2541-11e7-95cf-de22f791ca4b.png)

http://pedestrianiselondon.tumblr.com/post/20170547370/cycleway-provision-from-the-experts

Not clear exactly what the original source of this was. Page implies this is derived from CROW.

**Comment by mvl22** [comment]
![cid](https://cloud.githubusercontent.com/assets/361423/25199165/c2bbb54a-2541-11e7-8f7b-1ad76f456053.png)

Cycle Infrastructure Design, LTN 2/08, page 13. (Not considered by the cycling advocacy community as best practice nowadays.)

Linked to from this page, which has useful commentary:

http://rachelaldred.org/writing/thoughts/motor-traffic-volumes-when-do-cyclists-need-protected-space/

**Comment by mvl22** [comment]
Rachel Aldred's posting has useful discussion on PCUs (Passenger Car Units):

http://rachelaldred.org/writing/thoughts/motor-traffic-volumes-when-do-cyclists-need-protected-space/

**Comment by mvl22** [comment]
![crow_manual_speed_volume_matrix_2](https://cloud.githubusercontent.com/assets/361423/25199365/7a408d3a-2542-11e7-8c6a-566645b46ce5.jpg)

Table 14 from Dutch CROW Manual for Bicycle Traffic.

As found at:
https://www.cycleto.ca/news/let%E2%80%99s-finish-job-shaw-understanding-benefits-bicycle-boulevards-toronto

NB A new edition (2016) has been published since the above blog post was published:
https://www.crow.nl/publicaties/design-manual-for-bicycle-traffic
https://www.crow.nl/publicaties/_nieuw-design-manual-for-bicycle-traffic
so this table may have been superseded.

**Comment by mvl22** [comment]
![bool18_speed_volume](https://cloud.githubusercontent.com/assets/361423/25199479/dffed212-2542-11e7-8d2d-c9bc2353093d.png)

Nomograph, taken from Ontario’s Traffic Manual for bicycle infrastructure design. (I hadn't seen this before.)

https://www.cycleto.ca/news/let%E2%80%99s-finish-job-shaw-understanding-benefits-bicycle-boulevards-toronto

**Comment by mvl22** [comment]
![screen-shot-2014-12-15-at-09-50-56](https://cloud.githubusercontent.com/assets/361423/25199543/1557138e-2543-11e7-8a71-f694987638ac.png)

Welsh Cycling Audit Tool

Discussed here:
https://cyclebath.org.uk/2015/06/19/cycle-and-walking-audit-tools-a-present-from-cycle-bath-to-banes-councillors-and-council-officers/

(NB A 'Cycle Street' is nothing to do with us :) It refers to the dutch concept of a cycle-friendly street which vehicles are permitted to drive on as guests, with full priority given to bicycles.)

 Welsh Active Travel Design Guidance is at:
http://gov.wales/docs/det/publications/141209-active-travel-design-guidance-en.pdf

**Comment by Robinlovelace** [comment]
A graphical representation of infrastructure options:

![image](https://cloud.githubusercontent.com/assets/1825120/25218929/803b79c2-25a4-11e7-9eb9-59504d618c8a.png)

Definition of each type:

-   Off-Street Pathways are physically separated from motor vehicles and p rovide sufficient width
    and supporting facilities to be used by cyclists, pedestrians, and other non-motorized users. Off- street pathways can have paved (i.e. asphalt) or un paved surfaces. Pathway surfacing plays a
    large role in accessibility, and paved/firm surface s (i.e. asphalt, stone dust, fine limestone, or
    gravel screenings) are necessary for accessible pathways.

-   Cycle Tracks are physically separated from motor vehicle travel lanes but are located within the road right-of-way. Cycle tracks are a hybrid type b icycle facility combining the experience of an
    off-street path with the on-street infrastructure o f a conventional bicycle lane. In many cases
    cycle tracks are separated by landscaping or curbs
    from the sidewalk, facilitating separation
    between cyclists and pedestrians as well.

-   Local Street Bikeways are routes on streets with low vehicle speeds and
    volumes, which
    include a range of treatments ranging from relative ly basic facilities consisting of signage and
    pavement markings to bikeways with varying degrees of traffic calming implemented to improve
    safety for cyclists and other road users.

- Bicycle Lanes are separate lanes that are designated exclusively for bicycle travel and also
include pavement markings.

-   Shared Use Lanes provide direct routes for experienced cyclists along the outer lane of a
    roadway.

-   Shoulder Bikeways are typically found on streets without curb and gutter with shoulders wide
    enough for bicycle travel. Shoulder bikeways often, but not always, include signage alerting
    motorists to expect bicycle travel along the roadway.

This heavily cites CROW guidance.

Source: https://www.peelregion.ca/pw/construction/pdf/pedestrian-bicycle-facility-design-guidance.pdf

**Comment by mem48** [comment]
I've tried to do a quick synthesis of these different tables  
![image](https://cloud.githubusercontent.com/assets/15819577/25757188/7a4c1cfa-31c1-11e7-91d7-8ed7470a7759.png)

**Comment by mem48** [comment]
It's interesting the CROW distinguished between different levels of cycling, that feeds nicely into our use of PCT data. As there seems to be quite a lot of disagreement between these sources it might be better to have a (high/low) value for each possibility so that we can encapsulate the range of opinions.

**Comment by Robinlovelace** [comment]
My very simple starter for 10 based on this and given we have better l_bicycle data than PCU data, as discussed with @mem48 :

|speed_osm |l_low      |l_high            |
|:---------|:----------|:-----------------|
|low       |sign_posting |light_segregation |
|high      |do_nothing |superhighway      |

**Comment by Robinlovelace** [comment]
I envisage the threshold for `maxspeed` being 30mph, as documented here:  http://wiki.openstreetmap.org/wiki/Speed_limits

I envisage the threshold for `l_bicycle` being 2500 or a `slc_godutch >833` as roughly 1/3rd cycle traffic is commuting.

FYI the markdown for the table was produced with the following code, for reproducibility (sorry for using R where it's not strictly needed @mvl22  ; )

```r
library(knitr)
library(dplyr)

kable(frame_data(
  ~speed_osm, ~l_low, ~l_high,
  "low", "do_nothing", "light_segregation",
  "high", "do_nothing", "superhighway"
))
```

**Comment by mvl22** [comment]
> sorry for using R where it's not strictly needed

Nothing wrong with that!

**Comment by Robinlovelace** [comment]
Heads up @erathal - could be useful in later stages of Swiss LTS work.

**Comment by johnparkin28** [comment]
From the DMRB Interim Advice Note 
http://www.standardsforhighways.co.uk/ha/standards/ians/pdfs/ian195.pdf

See Table 2.2.11 on page 18 and
Table 2.4.2 on page 32

[ian195.pdf](https://github.com/cyipt/cyipt/files/1004116/ian195.pdf)

**Comment by mvl22** [comment]
> See Table 2.2.11 on page 18

![screen shot 2017-05-16 at 18 27 48](https://cloud.githubusercontent.com/assets/361423/26119571/90190046-3a65-11e7-9698-64f71c302906.png)

> Table 2.4.2 on page 32

![screen shot 2017-05-16 at 18 28 38](https://cloud.githubusercontent.com/assets/361423/26119561/8811ff06-3a65-11e7-85ad-309e62bb11e9.png)

**Comment by mvl22** [comment]
John says use DMRB, from these choices, because:

- Slightly more robust, as is about network for cyclists, rather than shared-use (as some of these propose)
- National, in sense that it relates to UK clearly.
- LAs use DMRB. Helps get sense that guidance is out there and applicable.
- John suggests is similar to CROW anyway: "equally as robust as that".

@johnparkin28, can you confirm this matches what you said?

**Comment by jf1** [comment]
[IAN195/16](http://www.standardsforhighways.co.uk/ha/standards/ians/pdfs/ian195.pdf) also has "Table 2.2.2 Minimum provision for cycle routes"
![image](https://user-images.githubusercontent.com/4711363/28172176-c7346a5c-67e2-11e7-998d-e10862dba49e.png)
That last line suggests there are at least 4 types of cycle track: stepped track (aka hybrid lane); lightly protected cycleway (using wands, plastic etc); fully protected cycleway (using kerbs); separated (by distance) cycleway.

**Comment by jf1** [comment]
For separated cycleways [IAN195/16](http://www.standardsforhighways.co.uk/ha/standards/ians/pdfs/ian195.pdf) has: "Table 2.3.3 Minimum Horizontal Separation between Carriageway and Cycle Tracks"
![image](https://user-images.githubusercontent.com/4711363/28172119-92242442-67e2-11e7-82c0-7a4360d2897d.png)

**Comment by Robinlovelace** [comment]
Thanks @jf1 that's useful input - looks like a good recommendation guidance document.
