### ISSUE TITLE
Regression Model

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#39]
Produce regression model fro Bristol with Business Variable

**Comment by Robinlovelace** [comment]
I can report good progress here - the framework is set-up. Based on conversation with stats people @VeetVoojagig (Mark Gilthorpe) and @WRobertLong the approach is to model the raw number cycling rather than the proportion.

@mem48 and @johnparkin28 please take a look here for the foundations of this: https://github.com/cyipt/cyipt/blob/master/scripts/model-uptake.md

Any feedback before a crack on with more advanced models welcome.

**Comment by johnparkin28** [comment]
Robin,

It is indeed correct to model the raw number not the proportion, I agree with that (in fact was doing a critique of someone elses stats on Monday and Tuesday and made exactly this point and re-did their calcs for them.)

When you do the distance decay I assume that it will be possible for the model to estimate the parameters (say ‘a’ and ‘b’ in something like the following: a.e^b. May be we have discussed this befre, but I suspect we will need a compound distance decay to take account of low cycling at under a mile. Something like {a.e^b][c.x^d] or whatever.

Not quite followed all the code! But looks impressive. Well done.

Regards
John Parkin CEng FICE FCIHT FCILT, Professor of Transport Engineering
University of the West of England, Centre for Transport and Society
Frenchay Campus, Coldharbour Lane Bristol, BS16 1QY, UK
t: +44 (0)117 32 86367 m: +44 (0)7848 029 902 Skype: john.parkin9, Twitter: @JohnParkin28 https://uk.linkedin.com/pub/john-parkin/6/840/89b
Publications: http://eprints.uwe.ac.uk/view/author/Parkin=3AJohn=3A=3A.html
http://www1.uwe.ac.uk/et/research/cts and https://www.facebook.com/ctsuwe

**Comment by mem48** [comment]
Can I just sound a note of caution,

While I agree with John that we should model numbers, not proportions, the nature of the data we have is that the number of cyclists will be a fraction of the total number of commuters. So a very simple model such as:

n_cyclists = n_commuters / 50 

Would probably provide quite a high-quality fit when using the typical measures of correlation. Whereas using

%_cyclists = 2%

Which is effectively the same model, would return a poor fit. 

I suggest that we model numbers of cyclists but include validation of proportions when developing the model.

I'd also suggest that some demographic data would be worth including such as age, gender, perhaps ethnicity etc.

A good test of the model would be if it was possible to predict the cycling between two nearby LSOA which have very good cycling infrastructure.  Thus explain why in some places 100% of journeys are not by bike.

**Comment by VeetVoojagig** [comment]
I confess to not entirely following your logic around the % versus counts - sorry if I'm being dim. 

With common denominators in fractions/proportions, the mathematical coupling (MC) that arises will distort any model-fit statistics for regression where MC occurs, just as it distorts any test statistics (e.g. p-value), so one cannot trust model-fit statistics when modelling coupled proportions. Don't know if that helps!

**Comment by Robinlovelace** [comment]
Many thanks @VeetVoojagig (for others - this is Alex Erath) - that helps. I think xgboost mitigates the problem of MC and that the explanatory variables are unrelated (we're not including current mode split just environmental and, eventually, social variables at the area level).

**Comment by Robinlovelace** [comment]
Good intro to xgboost: https://xgboost.readthedocs.io/en/latest/model.html

**Comment by VeetVoojagig** [comment]
That's very useful Robin. MC is averted by machine learning techniques in general, so useful that I explore this a lot more. Thanks

**Comment by Robinlovelace** [comment]
You might also find this useful - a worked example using xgboost to predict cycling level at the OD level using new variables we got from OSM and cyclestreets.net (could also apply this in new contexts - wonder where that could be useful ; ).

Any feedback on this very welcome - it's work in progress:

https://github.com/cyipt/cyipt/blob/master/model-uptake.md
