### ISSUE TITLE
Allocate PCU data to osm ids

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#43]
Good progress on this today - worth logging this when complete. There are a couple of ways of doing and PCU estimates can be allocated to only segments directly next to the monitors (I propose within 100m is a good proxy for 'touching') on roads we've matched on `ref` from OSM. Example of progress from Bristol on the A4018, which I used to cycle up and down from my house to Westbury-on-Trym:

![image](https://cloud.githubusercontent.com/assets/1825120/26530940/52ff90dc-43d7-11e7-8379-abf6ad750c94.png)

**Comment by Robinlovelace** [comment]
Online version - please take a look @johnparkin28 : http://rpubs.com/RobinLovelace/280371

**Comment by Robinlovelace** [comment]
Updated results - showing voronoi and intersecting spatial join methods: 

![image](https://cloud.githubusercontent.com/assets/1825120/26556586/4c49861e-4493-11e7-8350-083b2011f0c0.png)

**Comment by johnparkin28** [comment]
Robin,

Not quite sure what to make of it. It seems to show one of the main drags out of Bristol with the traffic flow converted t PCUs. And? I am missing something!

Regards
John Parkin CEng FICE FCIHT FCILT, Professor of Transport Engineering
University of the West of England, Centre for Transport and Society
Frenchay Campus, Coldharbour Lane Bristol, BS16 1QY, UK
t: +44 (0)117 32 86367 m: +44 (0)7848 029 902 Skype: john.parkin9, Twitter: @JohnParkin28 https://uk.linkedin.com/pub/john-parkin/6/840/89b
Publications: http://eprints.uwe.ac.uk/view/author/Parkin=3AJohn=3A=3A.html
http://www1.uwe.ac.uk/et/research/cts and https://www.facebook.com/ctsuwe

**Comment by Robinlovelace** [comment]
More tests - note the points without a road are outside the downloaded region:

![image](https://cloud.githubusercontent.com/assets/1825120/26558529/59e86200-44a1-11e7-8914-db69d38b0e22.png)

**Comment by Robinlovelace** [comment]
Hi John, this one seems much better - with the M roads having the highest PCUs: http://rpubs.com/RobinLovelace/280638

Tagging @johnparkin28 so you get a notification.

**Comment by Robinlovelace** [comment]
Here's the code btw: https://github.com/cyipt/cyipt/blob/master/trafficcounts/test-traffic.R

**Comment by Robinlovelace** [comment]
Update - got line geomtries in there now: 

![image](https://cloud.githubusercontent.com/assets/1825120/26836180/0f4bda10-4ad2-11e7-870f-8046df1127ec.png)

**Comment by Robinlovelace** [comment]
@mvl22 you do realise that only just over half of the records actually have a start and end point? The rest R just floating points FYI.

**Comment by Robinlovelace** [comment]
Updated results: http://rpubs.com/RobinLovelace/282788 and also pushed to the .csv file with this: 

```r
# save outputs
ways_t = select(ways_t, osm_id, aadt)
readr::write_csv(ways_t, "trafficcounts/trafficcounts-osm.csv")
```

**Comment by Robinlovelace** [comment]
https://github.com/cyipt/cyipt/blob/master/trafficcounts/trafficcounts-osm.csv

**Comment by mvl22** [comment]
> @mvl22 you do realise that only just over half of the records actually have a start and end point?

Didn't think it was that high, but as I alluded to when adding the data originally there are still some issues I need to resolve.

**Comment by Robinlovelace** [comment]
If in the next version of the data you could save numbers as numbers (i.e. `1` not `"1"`) that would simplify the code. As would doing it all in my favourite language I suspect ; )
