### ISSUE TITLE
Fix crashing download-osm

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#45]
download-osm crahes with some regions at:

res = osmdata_sf(q = q)

for  West Berkshire and Blackpool

**Comment by mem48** [comment]
Also fails on 
Cornwall,
Milton Keynes 
Northumberland
Chiltern
Christchurch
North Dorset
Rochford
Melton
Broadland
Spelthorne
Harrow
as download no data

**Comment by mem48** [comment]
Crashes on Fylde

**Comment by Robinlovelace** [comment]
Will look at this - still crashing?

**Comment by mem48** [comment]
Closing as code has had a massive refactor, will re-open if problem re-emerges
