### ISSUE TITLE
Typology of road types

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#49]
Creating a list of different road types and then linking them to what cycling interventions are possible and costs.

Initial work on creating these are some sample digrams.

https://github.com/cyipt/cyipt/blob/master/roadtypes.pptx

These are based on data from Bristol, looking at:

1) Road type
2) road direction (one-way/two-way)
3) number of lanes (in each direction)
4) cycle lanes / tracks (both / left / right / none )
5) bus lanes (both / left / right / none )
6) pavements (both / left / right / none)
7) cycling permitted (yes / no )

Future upgrades to include:

1)  integration with https://streetmix.net http://docs.shaunakkashyap.apiary.io/#reference 
2) Addition of tram lanes
3) Guessing of lane widths

**Comment by Robinlovelace** [comment]
I think we should also have these represented as a file in https://github.com/cyipt/cyipt/tree/master/input-data
