### ISSUE TITLE
Resurrect England Cycling Data 2011 project data

### ISSUE THREAD

**Issue by mvl22** [cyipt/cyipt#50]
http://wiki.openstreetmap.org/wiki/England_Cycling_Data_project

Action Martin

**Comment by mvl22** [comment]
Now available at:
https://github.com/cyclestreets/dft-england-cycling-data-2011
:)

You basically want the file `/dft-england-cycling-data-2011.geojson`.

**Comment by Robinlovelace** [comment]
Many thanks - seems done to me!
