### ISSUE TITLE
Website Wish List

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#53]
A place to store ideas and wish list for the website UI / functionality

**Back-end functions**

- [ ] JS clean up and remove duplicated code

- [ ] Automatic creation of legends from the colour scheme

**General UI**

- [ ] Edit the OSM button, either a generic or preferably one that takes you to the same location that you are currently viewing

- [ ] True responsive design the works on mobile (by folding away the sidebar?)

- [ ] Make warning message more elegant and dismissable

- [ ] Data sliders, and double-ended data sliders (nice example https://www.kayak.co.uk/flights/MAN-LON/2017-12-01/2017-12-08 note the mini histograms that appear when using the slider)

- [ ] Better way to layout the sidebar to handle many layers especially on a small screen

- [ ] Help button for each data layer

- [ ] Zoom in prompt for layer not viewable when zoomed out

- [ ] Highlight object on mouse over

- [ ] Simple search to find towns and cities and or geolocation

**API**

- [ ]  Support (require) API key and system to sign up for API key

- [ ] Different limits based on which API provided

- [ ] Data download option, larger amounts of data but infrequently

- [ ] Improve data comression

- [ ] Improve data recovery speed (indexes etc)

- [ ] Smoother use of geometry simplification

- [ ] At lower zooms provide a small area of data rather than no data like https://bikedata.cyclestreets.net/cycleability/#15/53.8097/-1.5233/opencyclemap

**Details UI**

To save pushing all the attributes to the browser use the ID field to create a new Details page.

- [ ] Mini Map showing just one feature

- [ ] Table with full set of attributes

**Collisions UI**

- [ ] Similar to https://www.cyclestreets.net/collisions/reports/200901CP00139/

**Comment by Robinlovelace** [comment]
This is a pretty comprehensive list and falls largely into the UI side. You up for presiding over this @mvl22 ?

**Comment by mem48** [comment]
Moved to the cyipt-website repo
