### ISSUE TITLE
Create function to remove existing infra

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#57]
Will be beneficial for estimating uptake. I suggest calling it `remove_cycle_infra()` - unless it's already done or @mem48 has different plans...

**Comment by mem48** [comment]
I don't understand, what this function would do. T remove cycle infrastructure you would simply set $cycleway.left and $cycleway.right to = "no", it doesn't really need a function of its own.

**Comment by Robinlovelace** [comment]
A function may seem like overkill for this but it may make life easier and scripts more concise. 

Based on what you say I think the following function will do the job - if you think of any easy-to-catch edge cases based on http://wiki.openstreetmap.org/wiki/Bicycle let me know. Reproducible example below created using reprex:

``` r
remove_cycle_infra = function(ways) {
  ways$cycleway.left = "no"
  ways$cycleway.right = "no"
  return(ways)
}

# test data
ways = readRDS("~/cyipt/cyipt-bigdata/osm-clean/BristolCityof/osm-lines.Rds")
summary(as.factor(ways$cycleway.left))
#>         lane           no share_busway        track 
#>          104        18102           93            7
ways = remove_cycle_infra(ways)
summary(as.factor(ways$cycleway.left))
#>    no 
#> 18306
```
