### ISSUE TITLE
Optimise prep_osm.R

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#58]
Now we are using larger TTWAs rather than LAs the function is far too slow, taking many hours per region.

**Comment by mem48** [comment]
@Robinlovelace this may be of interest for R courses and books, as the performance gains on bid datasets are massive.

**Comment by Robinlovelace** [comment]
Awesome - great work. Will test on my Hereford dataset in due course and keep it in mind for the 3rd part, which we need to get on from January: https://github.com/Robinlovelace/geocompr/milestones

**Comment by mem48** [comment]
@Robinlovelace  Also, I've just pushed an update to my proposed chapter https://github.com/mem48/geocompr/blob/master/14-efficient-geocomputation.Rmd

**Comment by Robinlovelace** [comment]
Great, many thanks.
