### ISSUE TITLE
Estimate costs

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#6]

**Comment by mem48** [comment]
Cost estimates need to align with the OSM dataset classification see http://wiki.openstreetmap.org/wiki/Bicycle

**Comment by mem48** [comment]
Moving to WP2 as cost come after Invention Idetification

**Comment by Robinlovelace** [comment]
Great progress on this by the sounds of it. @mem48 could you share the latest on this so I can take a look.

**Comment by mem48** [comment]
Costs are based on this file https://github.com/cyipt/cyipt/blob/master/input-data/costs.csv

**Comment by Robinlovelace** [comment]
Thanks, very useful.

**Comment by mvl22** [comment]
This just came up in my twitter feed today:

Cambridgeshire County Council:
Local Highway Improvement Initiative
Indicative Cost of Solutions

Page 4:
https://democracy.cambridge.gov.uk/documents/s31347/APPENDIX%20C%20-%20LHI%20Application%20Guidance%20Notes%202016-17.pdf

![costs](https://user-images.githubusercontent.com/361423/33728844-b32bcfdc-db73-11e7-83d2-0e8d2612a5e1.png)

Cc @mem48
