### ISSUE TITLE
Build for new regions

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#62]
To be close when this is done - can open new ones:

- [ ] D2N2
- [ ] West Yorkshire / TfN region
- [ ] Bath

**Comment by mvl22** [comment]
Could we add Bath please?

**Comment by Robinlovelace** [comment]
Added - should be easy. Let us know @mem48

**Comment by mem48** [comment]
No hard to do but is there any urgency to these requests? If my computer is building regions then I'm not adding features. with the switch TTWAs we have a good chunk of the country covered.

**Comment by mem48** [comment]
Its working hard already 

![image](https://user-images.githubusercontent.com/15819577/32851513-0831d0a6-ca2d-11e7-9858-167cc6fd59e9.png)

**Comment by Robinlovelace** [comment]
Sounds like @mem48 is on it - pls close when it's up and tested Malcolm.

**Comment by mem48** [comment]
Closing as national build is in progress
