### ISSUE TITLE
Fix cross region flows problem

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#63]
The switch to TTWAs has mitigated but not solved the cross-regional flows problem. THere are still many lines and some people that cross regions. This makes calculating the effect complex and needs a solution.

One possible way is to only allow calculation of uptake if the surrounding regions have been built.

**Comment by Robinlovelace** [comment]
Sounds like a good fix. Also making it easy to add new regions would mitigate the impacts of this if it is not fixed (not essential before March).

**Comment by mvl22** [comment]
Will that mean a re-entrant algorithm to deal with the fact that the initial areas by definition won't have surrounding regions, i.e. regenerate the initial areas?

**Comment by mem48** [comment]
No should be simpler than that. As we can run the early stages independently and just build in a check for the later stages that says, "I don't have all the data I need please build the following regions first"

**Comment by Robinlovelace** [comment]
No we only ever run one region at a time. If there's an LA between the avon and gloucester TTWAs (unlikely) we just rebuild a custom version is my solution. Really liking how the TTWAs are performing so glad Malcolm twigged the need for them and that I could point to an officially supported solution.

**Comment by mem48** [comment]
As quietness is not actively being used this is no longer an issue, so closing
