### ISSUE TITLE
Road width data for Cambridge very spotty

### ISSUE THREAD

**Issue by mvl22** [cyipt/cyipt#67]
The road width data for Cambridge is very spotty - can you have a look at this, @mem48?

https://www.cyipt.bike/width/#15/52.2014/0.1242/mapnik

At present I haven't been able to verify the work on that layer as I'm obviously familiar with Cambridge's roads rather than Bristol.

**Comment by Robinlovelace** [comment]
Interesting that it has many small paths but not the roads, as illustrated below, well spotted. Note Malcolm is now away until 8th Jan but may (if we're lucky) pick-up on this and provide an explanation before then.

![image](https://user-images.githubusercontent.com/1825120/34252139-4fee461c-e63a-11e7-9150-75692c8bb5a1.png)

**Comment by mem48** [comment]
I know why this is and have fixed the problem, it will go away when I next update the database
