### ISSUE TITLE
Cycle streets on some large, heavily trafficked roads

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#70]

**Comment by Robinlovelace** [comment]
E.g. Cowley Rd in Oxford:

![image](https://user-images.githubusercontent.com/1825120/34965681-d66e7762-fa4d-11e7-8270-1409781cf2c4.png)

**Comment by Robinlovelace** [comment]
And Clifton Suspension Bridge which already has cycle lanes on it plus is heavily trafficked (I know from experience). The latter issue will be resolved when we have network-wide traffic level estimates. The former can be solved by setting a rule that cycle streets should not go where there is already a cycle lane, I imagine.

![image](https://user-images.githubusercontent.com/1825120/34966524-3c90e22c-fa54-11e7-8d2d-ca8455831cbc.png)

**Comment by mem48** [comment]
In Oxford it is probably due to the lack of traffic data on that part of the road, and a drop in the speed limit to 20 mph, which mean CyIPT sees it as a very different road type. Probably need to add a speed limit layer to CyIPT to highlight this as a key import

**Comment by mem48** [comment]
Same with the Clifton Bridge having a 20 mph limit and no traffic data, also it has footpaths not cycle lanes

**Comment by Robinlovelace** [comment]
Ah OK - I didn't realise walking paths count as existing infra. Is that deliberate? It did have cycle lanes as far as I remember when I used in (2004 - 2008) but they were pretty poorly marked I seem to remember so not surprised if they're not in the OSM dataset. Best solution: get better traffic estimates - I suspect that **dodgr** by @mpadge trained against known data would be a good method for estimating route-wide traffic levels. I suggest we add this to the wishlist for Phase III and close this for now - worth flagging though.

**Comment by mem48** [comment]
Martin and I are reviewing the existing infrastructure layer because it is not working well. Better traffic data is a must, is there any update on the Halogen Data?

**Comment by Robinlovelace** [comment]
Closing for now pending better road traffic data.
