### ISSUE TITLE
Create e-mail address

### ISSUE THREAD

**Issue by mvl22** [cyipt/cyipt#74]
E-mail address. MLS to put into server deployment.

**Comment by Robinlovelace** [comment]
cyipt@ I imagine. Or info@ ...

**Comment by mvl22** [comment]
I was going to use info@.

I've edited your comment to remove active e-mail addresses for the benefit of not attracting spam...

**Comment by Robinlovelace** [comment]
Good shout, many thanks - don't want another spam-filled inbox!
