### ISSUE TITLE
Unique scheme IDs / names

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/cyipt#80]
Problem: currently if someone identifies their 'top 3' schemes it's difficult and ambiguous for them to communicate them. 

Proposed solution: provide a uniqe ID or perhaps better a uniqe name that exists only for that scheme. Print that at the top of the scheme when selected.

Example: my top route in leeds goes down Scott Hall Road, but the first piece of information you see about it is that it's in Leeds, which many people will know already. I proposed the first row of data is `Name: Scott Hall Road` or `Scott Hall Road Leeds`. The latter option could mean we could replace the current top line as it contains already the info that it's in Leeds:

![image](https://user-images.githubusercontent.com/1825120/37553102-f0fb8a1c-29b8-11e8-86fb-0736249c2586.png)

Clearly this depends on having a unique name per scheme.

**Comment by Robinlovelace** [comment]
The wider benefit of this I've been thinking about: in the same way that DECC's 2050 carbon calculator allows you to save scenarios of the future to share, this could allow people to share their scenarios for change. This is a wider issue but solving this smaller one is a *sin qua non* so I'll hold my horses before opening a ticket on that more ambitious (but more useful) issue. For today (demonstrating CyIPT to the public at [Be Curious](http://www.leeds.ac.uk/download/667/be_curios_2018)) I will simply take a note of the road names.

**Comment by mvl22** [comment]
Ah right, I actually took out the IDs from public display, so can re-add potentially, but I did so because they presumably aren't stable. This would need some algorithm work to ensure they are stable, but I can't think how we would make them so - even using OSM IDs (e.g. longest Way present) wouldn't work because the longest ID could change from build to build.

**Comment by Robinlovelace** [comment]
One to think about + discuss. Being able to have a 'vision of the core network' represented by, say 10 ids, would be useful.

**Comment by jf1** [comment]
I think something is better than nothing, even if it changes between builds, so hope the previous IDs can be restored for Friday.

For the longer-term (for CyIPT and beyond) I've envisaged a way to create persistent segment IDs based on ITN identifiers (osgb4000... codes). Processing OS Open and OSM data could create a lookup table then subsequent runs can create new IDs where required (newly opened, closed, joined, split or renamed roads), linking them to previous ID/s when appropriate.

**Comment by mvl22** [comment]
> the previous IDs can be restored for Friday

@Robinlovelace @mem48 Please thumb up if you think I should do this. I'm not convinced of the value of exposing IDs generated automatically in sequence by the script - they are likely to change every time surely.

**Comment by mem48** [comment]
The IDs are not stable and I would not recommend doing this as it would almost certainly cause confusion. In fact, the schemes themselves are not entirely stable, and changes in the OSM could cause the schemes to cluster differently.

A simple example is:
A road which has a cycle lane along part (but not all) of the road, but has not been tagged in the OSM. CyIPT recommends one scheme a cycle lane on the whole road. Then the OSM is updated with the missing infrastructure. CyIPT is rerun and now creates two schemes, one on each side of the existing infrastructure.

**Comment by jf1** [comment]
It's clear that persistent IDs are the optimum solution however this doesn't mean that having no IDs would be preferable to having some form of reference, even if that reference is only valid for that build.

Consider this example: a user and their colleague are discussing a proposed scheme, and they've shared links with each other but there are at least two schemes visible in that view, possibly on the same road, and user A wants to ensure user B is looking at the same proposal before they engage in a conversation about it.

**Comment by mem48** [comment]
@jf1 I still think this is a bad idea, we are still in the prototype stage, and offer no reliability or stability guarantees. In your example user A could send an ID and the user B use the ID to look at a completely different scheme as I updated CyIPT during the intervening time.

Any IDs that we share would have a short random life and change without warning or acknowledgement. There would be no way to view the old data or convert the old ID to a new ID or vice versa.

Sharing the URL is simple, stable, and persistent. It also would be easy enough to zoom in until only one scheme is visible, or for users to describe the scheme they mean along with the link.

**Comment by jf1** [comment]
Obviously it's your call however I still think that some ID is better than no ID. Especially as you're at the prototype stage their transient nature seems reasonable - just needs a note in the manual to confirm and explain this.

I deliberately used the example of two people looking as the same view at the same time, so even if the ID was different from what it was yesterday the conversation would be able to go ahead without any confusion.

> sharing the URL... zoom in until only one scheme is visible

My example was a conversation about just one scheme - there could easily be a few schemes that the users want to specifically refer to in a discussion.

> updated CyIPT during the intervening time

I think this is an issue in its own right - is a version number or time-stamp exposed somewhere, so users can be aware when there's been a (possible) change in the underlying data?

**Comment by mem48** [comment]
> is a version number or time-stamp exposed somewhere, so users can be aware when there's been a (possible) change in the underlying data?

Nope, and if there was one you would see that the database is being updated all the time

**Comment by mvl22** [comment]
Malcolm has summarised my own concerns well. I've put some effort into permalink support so I think that should be good enough for now.
