### ISSUE TITLE
The mysterious case of Manchester 10 mph roads

### ISSUE THREAD

**Issue by mem48** [cyipt/cyipt#82]
The centre of Manchester has a lot of 10 mph residential roads, these are not tagged as 10 mph in the OSM to CyIPT must be guessing that they are 10 mph.

 But CyIPT should guess 30 mph for residential roads, this does not appear to be happening in other towns

https://www.cyipt.bike/existing/#16/53.4787/-2.2436/mapnik

**Comment by Robinlovelace** [comment]
Any ideas @jf1?

**Comment by jf1** [comment]
Looking at: https://www.openstreetmap.org/edit?way=4721498#map=19/53.47863/-2.25272

I notice the `maxspeed` value is `20 mph` rather than `20` - might that be the cause?

**Comment by mem48** [comment]
I don't think so, the code handles the mph / kph issue. 

For context the default unit in OSM is kph so "30" means 30 kph and only "30 mph" means 30 mph, however in practice in the UK all speed limits are in mph and you will see "30","30mph","30 mph" all used. So the code cleans these all to simple numbers in mph.

The mystery here is when no speed limit is provided, CyIPT has guessing functions to fill in the gaps. See the difference between.

http://product.itoworld.com/map/124?lon=-2.24455&lat=53.47929&zoom=16&open_sidebar=share_menu

and

https://www.cyipt.bike/#16/53.4785/-2.2476/mapnik with the speed limits

the itoworld map has lots of grey (no data) whereas CyIPT always has a value. It is just odd that this is only wrong in Manchester. However, it is likely to have a big effect on the results as speed limits significantly affect both the cycling infrastructure selection and the uptake model.

**Comment by mem48** [comment]
I have a working hypothesis that Manchester (as one of the test regions) is using older data than the rest of the country and this is caused by a bug that has now been fixed. Which Is why I can't find a flaw in the code.

So I'm going to rerun Manchester and see if the results are different.
